#!/usr/bin/env python3

import os
from pathlib import Path

IGNORE = [
#     'e-feMorphology-012', # will timeout on CI
#     'e-svg-007', # invalid encoding
#     'e-svg-034', # invalid size
#     'e-svg-035', # invalid size
#     'e-svg-036', # invalid size

#     'e-svg-009',
#     'e-svg-010',
#     'e-svg-011',
#     'e-svg-015',
#     'e-svg-017',
    'tests/filters/feMorphology/huge-radius',
    'tests/structure/svg/negative-size',
    'tests/structure/svg/no-size',
    'tests/structure/svg/zero-size',
    'tests/structure/svg/not-UTF-8-encoding',
]

print('// This file is auto-generated by gen-tests.py')
print()
print('#![allow(non_snake_case)]')
print()
print('use crate::render;')
print()

files = sorted(list(Path('tests').rglob('*.svg')))
for file in files:
    file = str(file).replace('.svg', '')

    if file in IGNORE:
        continue

    fn_name = file.replace('tests/', '')
    fn_name = fn_name.replace('/', '_')
    fn_name = fn_name.replace('-', '_')
    fn_name = fn_name.replace('=', '_eq_')
    fn_name = fn_name.replace('.', '_')
    fn_name = fn_name.replace('#', '')

    print(f'#[test] fn {fn_name}() {{ assert_eq!(render("{file}"), 0); }}')
