= SVG Document Structure
:toc:

== Intro

One of the core ideas of the _resvg_ is that the input SVG will be
converted into as simple SVG as possible before rendering.
Which helps to implement a new backend easily.

This SVG represented via `RenderTree` structure.
It's an immutable container with all elements and attributes resolved.

Even through it doesn't follow the SVG spec and supports only a tiny
SVG subset - it's still a completely valid SVG structure, that can be
easily dumped into the SVG file.

And it makes _resvg_ preprocessor easier to understand and debug when
you can see the resulting structure via usual SVG data.

== Example

This SVG contains most of the elements and attributes that will be left after
preprocessing.

```xml
<svg
   height="300"
   viewBox="0 0 300 300"
   width="300"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:resvg="https://github.com/RazrFalcon/resvg"
   resvg:version="0.1.0">
  <defs>
    <linearGradient
       id="linearGradient1"
       gradientUnits="objectBoundingBox"
       spreadMethod="pad"
       x1="0"
       x2="1"
       y1="0"
       y2="0">
      <stop
         offset="0"
         stop-color="#ffffff"
         stop-opacity="1"/>
      <stop
         offset="1"
         stop-color="#000000"
         stop-opacity="1"/>
    </linearGradient>
  </defs>
  <path
     d="M 5 5 L 105 5 L 105 105 L 5 105 Z"
     fill="url(#linearGradient1)"
     stroke="none"/>
  <g
     opacity="0.5">
    <path
       d="M 305 65 C 305 37.38576251 282.61423749 15 255 15 C 227.38576251 15 205 37.38576251 205 65 C 205 92.61423749 227.38576251 115 255 115 C 282.61423749 115 305 92.61423749 305 65 Z"
       fill="#ff0000"
       opacity="0.5"
       stroke="none"/>
    <path
       d="M 340 120 C 340 92.38576251 317.61423749 70 290 70 C 262.38576251 70 240 92.38576251 240 120 C 240 147.61423749 262.38576251 170 290 170 C 317.61423749 170 340 147.61423749 340 120 Z"
       fill="#00ff00"
       opacity="0.5"
       stroke="none"/>
    <path
       d="M 370 65 C 370 37.38576251 347.61423749 15 320 15 C 292.38576251 15 270 37.38576251 270 65 C 270 92.61423749 292.38576251 115 320 115 C 347.61423749 115 370 92.61423749 370 65 Z"
       fill="#0000ff"
       opacity="0.5"
       stroke="none"/>
  </g>
  <text>
    <tspan
       text-anchor="middle"
       x="150"
       y="180">
      <tspan
         fill="#000000"
         font-family="Times New Roman"
         font-size="12"
         stroke="none">
        Complex
      </tspan>
      <tspan
         fill="#008000"
         font-family="Times New Roman"
         font-size="12"
         stroke="none">
        text
      </tspan>
    </tspan>
  </text>
  <image
     height="16"
     width="16"
     x="140"
     xlink:href="data:image/png;base64,
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhk
iAAAAAlwSFlzAAACXQAAAl0BwXvr0wAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3Nj
YXBlLm9yZ5vuPBoAAALrSURBVDiNdZNNSBt5GMZ/M4ylGTClWNBDQ4ySQZqACm4O
xYUlVAzogKfmorhID0LViyd7CFKKC+Khe1ikBhNZegh4KCoLCzbEBpeKJw9Rlg6p
SSC4sm1q41d0MvPvIf3cj+f68jw8vO/vlcSz70zkKwrfSMBxgfelQyRh4rzK/ymv
fDELqJSgeg7VMx7/9jc/pRqQgAfBt0wE/zPA/dksSntEk0e8fA0hHzxar8fIGggh
0FrdNDpP+H0XbrfAvW6QpJpTBqBSIpo84mn+e0ITCSIvNM4qVSzLwrIsTitVIi80
QhMJfs11s/jHlwq1BtY5L1/D/Yn7hMNhVFVlYGCAQqGAEILLy0vm5ubQdR3btnn+
yyb3uj8HCDDPCPkgEomgqiq6rrO4uIgs1wrGYjF0XWd1dZXp6Wke/fD1vp/eFI/v
Im5crxcOh0PIsiyWlpbEPxWPx4Usy8LhcIgb1+vFz2GEeIJQ3pcOmUk18CprYFkW
+XweWZYRQiB93JQQgvb2dra3t3G73UiSxK02jR9vl1CMv0zevH2H1+slGAzi8XhY
W1sjFAqRTqdRFIVAIEAqlaKvrw/DMEin0xwdlXl1CNKfDxF3Fm4yODjI+Pg4u7u7
NDU1sb+/TyaToa6uDpfLRWdnJ7lcjo6ODmZnZ1lZWSERztauoCgKmqaRTCaJxWIE
AgEaGxvxer0oikI2myUYDDI6OorL5cK2bRRF4fj8IwfFYpGFhQV6enqYmZmhWCyy
sbFBc3MzLS0tGIbBxcUFra2tTE1N0dXV9YndWgPTNNna2kLTNHp7e5mfn8fn89HW
1oZlWWxubmJZFsvLy/j9fmRZ5uDg4CsSgcnJSRKJBKqqYts25XKZTCbDzs4OhUIB
p9NJf38/fr8fwzAol8s1kK45alxHo1E8Hg9DQ0MMDw9TqVRYX1/HNE1OTk4YGRlh
bGyMvb094vE4kgT1V0EST8jtv8FdOv33q51egmWDBBxXvp1dU8HTQPUDlrxR46Ck
wpEAAAAASUVORK5CYII="
     y="10"/>
</svg>

```

You can generate it by yourself using:

```
rendersvg doc/complete.svg --pretend --dump-svg dump.svg
```

*Note:* `xml:space` and `text-decoration` attributes isn't exported now.

== Elements

=== svg

The `svg` element is the root element of the document.
It's defined only once and can't be nested, unlike by the SVG spec.

Supported children: `defs`, `g`, `path`, `text` and `image`.

=== defs

Supported children: `linearGradient`, `radialGradient`, `clipPath` and `pattern`.

=== linearGradient

Gradient has all attributes resolved and at least two `stop` children.

Gradient doesn't have `xlink:href` attribute because all attributes and `stop` children
are already resolved and copied to the gradient.

=== radialGradient

See `linearGradient`.

=== pattern

Pattern defines a texture image that can be used by `fill` and `stroke`.

Supported children: `g`, `path`, `text` and `image`.

=== clipPath

`clipPath` defines a 1-bit mask using children elements.

Supported children: `path` and `text`.

=== g

The group element indicates that a new canvas should be created.
All groups children elements will be rendered on it and then merged to
the parent canvas.

Since it's pretty expensive, especially memory wise, _resvg_
will remove as many groups as possible.
All the remaining one will indicate that a new canvas must be created.

=== path

First, the _resvg_ preprocessor will convert all the shapes into paths.
Then it will simplify path's data so it will contain only absolute
MoveTo, LineTo, CurveTo and ClosePath segments.

The `path` element can have <<fill_attrs, filling>> and
<<stroke_attrs,stroking>> attributes.

=== text

The text is one of the most complex parts of the SVG.
_resvg_ will modify the input element and its children a lot.

The simplest `text` element like `<text>Text</text>` will be converted to:

```xml
<text>
  <tspan
     x="0"
     y="0">
    <tspan
       fill="#000000"
       font-family="Times New Roman"
       font-size="12"
       stroke="none">
      Text
    </tspan>
  </tspan>
</text>
```

In _resvg_, the `text` element is just a container for
https://www.w3.org/TR/SVG11/text.html#TextChunk[text chunks],
represented via `tspan`.
So all `text` elements will have a three-level structure:

* `text` - container
** `tspan` - text chunk
*** `tspan` - text container

The `text` itself can have only a `transform` attribute.

_Text chunk_ can have `x`, `y` and `text-anchor` attributes.

And the _text container_ can have <<fill_attrs, filling>>,
<<stroke_attrs,stroking>>, <<font_attrs,font>> and `text-decoration` attributes.

// TODO: explain text-decoration

=== image

An image can have base64 encoded data or a path to an image.

== Attributes

[[fill_attrs]]

=== Filling attributes

Filling attributes refers to:

- `fill`
- `fill-opacity`
- `fill-rule`

[[stroke_attrs]]

=== Stroking attributes

Stroking attributes refers to:

- `stroke`
- `stroke-dasharray`
- `stroke-dashoffset`
- `stroke-miterlimit`
- `stroke-opacity`
- `stroke-width`
- `stroke-linecap`
- `stroke-linejoin`

[[font_attrs]]

=== Font attributes

Font attributes refers to:

- `font-family`
- `font-size`
- `font-style`
- `font-variant`
- `font-weight`
- `font-stretch`
