[package]
name = "codegen"
version = "0.1.0"
authors = ["Yevhenii Reizner <razrfalcon@gmail.com>"]
license = "MIT"
edition = "2021"

[workspace]

[[bin]]
name = "codegen"
path = "main.rs"

[dependencies]
phf = "0.7.22"
phf_codegen = "0.7.22"
itertools = "0.7"
