// This file is autogenerated. Do not edit it!
// See ./codegen for details.

use std::fmt;

#[derive(Clone, Copy, PartialEq)]
pub enum EId {
    A,
    Circle,
    ClipPath,
    Defs,
    Ellipse,
    FeBlend,
    FeColorMatrix,
    FeComponentTransfer,
    FeComposite,
    FeConvolveMatrix,
    FeDiffuseLighting,
    FeDisplacementMap,
    FeDistantLight,
    FeFlood,
    FeFuncA,
    FeFuncB,
    FeFuncG,
    FeFuncR,
    FeGaussianBlur,
    FeImage,
    FeMerge,
    FeMergeNode,
    FeMorphology,
    FeOffset,
    FePointLight,
    FeSpecularLighting,
    FeSpotLight,
    FeTile,
    FeTurbulence,
    Filter,
    G,
    Image,
    Line,
    LinearGradient,
    Marker,
    Mask,
    Path,
    Pattern,
    Polygon,
    Polyline,
    RadialGradient,
    Rect,
    Stop,
    Style,
    Svg,
    Switch,
    Symbol,
    Text,
    TextPath,
    Tref,
    Tspan,
    Use
}

static ELEMENTS: Map<EId> = Map {
    key: 3558916427560184125,
    disps: &[
        (1, 13),
        (5, 3),
        (0, 19),
        (6, 24),
        (0, 0),
        (0, 3),
        (0, 1),
        (11, 10),
        (0, 21),
        (0, 0),
        (5, 0),
    ],
    entries: &[
        ("feConvolveMatrix", EId::FeConvolveMatrix),
        ("tspan", EId::Tspan),
        ("style", EId::Style),
        ("feFuncB", EId::FeFuncB),
        ("rect", EId::Rect),
        ("marker", EId::Marker),
        ("feDiffuseLighting", EId::FeDiffuseLighting),
        ("g", EId::G),
        ("symbol", EId::Symbol),
        ("pattern", EId::Pattern),
        ("path", EId::Path),
        ("feFuncR", EId::FeFuncR),
        ("a", EId::A),
        ("textPath", EId::TextPath),
        ("use", EId::Use),
        ("feFuncA", EId::FeFuncA),
        ("tref", EId::Tref),
        ("circle", EId::Circle),
        ("fePointLight", EId::FePointLight),
        ("defs", EId::Defs),
        ("feTile", EId::FeTile),
        ("image", EId::Image),
        ("stop", EId::Stop),
        ("feGaussianBlur", EId::FeGaussianBlur),
        ("feFlood", EId::FeFlood),
        ("polyline", EId::Polyline),
        ("feComponentTransfer", EId::FeComponentTransfer),
        ("linearGradient", EId::LinearGradient),
        ("feFuncG", EId::FeFuncG),
        ("ellipse", EId::Ellipse),
        ("clipPath", EId::ClipPath),
        ("feMerge", EId::FeMerge),
        ("feSpotLight", EId::FeSpotLight),
        ("feBlend", EId::FeBlend),
        ("svg", EId::Svg),
        ("feColorMatrix", EId::FeColorMatrix),
        ("feTurbulence", EId::FeTurbulence),
        ("feSpecularLighting", EId::FeSpecularLighting),
        ("switch", EId::Switch),
        ("feMorphology", EId::FeMorphology),
        ("feImage", EId::FeImage),
        ("feMergeNode", EId::FeMergeNode),
        ("feOffset", EId::FeOffset),
        ("polygon", EId::Polygon),
        ("feComposite", EId::FeComposite),
        ("radialGradient", EId::RadialGradient),
        ("line", EId::Line),
        ("feDisplacementMap", EId::FeDisplacementMap),
        ("feDistantLight", EId::FeDistantLight),
        ("mask", EId::Mask),
        ("text", EId::Text),
        ("filter", EId::Filter),
    ],
};

impl EId {
    pub fn from_str(text: &str) -> Option<EId> {
        ELEMENTS.get(text).cloned()
    }

    #[inline(never)]
    pub fn to_str(&self) -> &'static str {
        ELEMENTS.key(self)
    }
}

impl fmt::Debug for EId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.to_str())
    }
}

impl fmt::Display for EId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

#[derive(Clone, Copy, PartialEq)]
pub enum AId {
    Amplitude,
    BaselineShift,
    Class,
    ClipPath,
    ClipRule,
    ClipPathUnits,
    Color,
    ColorInterpolationFilters,
    Cx,
    Cy,
    D,
    Direction,
    Display,
    Dx,
    Dy,
    Exponent,
    Fill,
    FillOpacity,
    FillRule,
    Filter,
    FilterUnits,
    FloodColor,
    FloodOpacity,
    FontFamily,
    FontSize,
    FontStretch,
    FontStyle,
    FontVariant,
    FontWeight,
    Fx,
    Fy,
    GradientTransform,
    GradientUnits,
    Height,
    Href,
    Id,
    ImageRendering,
    In,
    In2,
    Intercept,
    K1,
    K2,
    K3,
    K4,
    LetterSpacing,
    MarkerEnd,
    MarkerMid,
    MarkerStart,
    MarkerHeight,
    MarkerUnits,
    MarkerWidth,
    Mask,
    MaskContentUnits,
    MaskUnits,
    Mode,
    Offset,
    Opacity,
    Operator,
    Orient,
    Overflow,
    PatternContentUnits,
    PatternTransform,
    PatternUnits,
    Points,
    PreserveAspectRatio,
    PrimitiveUnits,
    R,
    RefX,
    RefY,
    RequiredExtensions,
    RequiredFeatures,
    Result,
    Rotate,
    Rx,
    Ry,
    ShapeRendering,
    Slope,
    Space,
    SpreadMethod,
    StartOffset,
    StdDeviation,
    StopColor,
    StopOpacity,
    Stroke,
    StrokeDasharray,
    StrokeDashoffset,
    StrokeLinecap,
    StrokeLinejoin,
    StrokeMiterlimit,
    StrokeOpacity,
    StrokeWidth,
    Style,
    SystemLanguage,
    TableValues,
    TextAnchor,
    TextDecoration,
    TextRendering,
    Transform,
    Type,
    Values,
    ViewBox,
    Visibility,
    Width,
    WordSpacing,
    WritingMode,
    X,
    X1,
    X2,
    Y,
    Y1,
    Y2
}

static ATTRIBUTES: Map<AId> = Map {
    key: 3213172566270843353,
    disps: &[
        (0, 27),
        (0, 85),
        (3, 38),
        (0, 0),
        (0, 1),
        (3, 53),
        (1, 25),
        (0, 20),
        (9, 110),
        (2, 1),
        (0, 12),
        (0, 23),
        (3, 13),
        (0, 19),
        (1, 39),
        (2, 9),
        (0, 2),
        (0, 0),
        (11, 32),
        (46, 47),
        (6, 77),
        (0, 10),
        (10, 8),
    ],
    entries: &[
        ("transform", AId::Transform),
        ("in2", AId::In2),
        ("k1", AId::K1),
        ("word-spacing", AId::WordSpacing),
        ("id", AId::Id),
        ("d", AId::D),
        ("cy", AId::Cy),
        ("marker-mid", AId::MarkerMid),
        ("slope", AId::Slope),
        ("stroke-dashoffset", AId::StrokeDashoffset),
        ("text-rendering", AId::TextRendering),
        ("stop-opacity", AId::StopOpacity),
        ("requiredExtensions", AId::RequiredExtensions),
        ("baseline-shift", AId::BaselineShift),
        ("preserveAspectRatio", AId::PreserveAspectRatio),
        ("cx", AId::Cx),
        ("stroke-miterlimit", AId::StrokeMiterlimit),
        ("letter-spacing", AId::LetterSpacing),
        ("flood-color", AId::FloodColor),
        ("stop-color", AId::StopColor),
        ("clip-path", AId::ClipPath),
        ("ry", AId::Ry),
        ("clipPathUnits", AId::ClipPathUnits),
        ("stroke-linecap", AId::StrokeLinecap),
        ("fx", AId::Fx),
        ("values", AId::Values),
        ("color", AId::Color),
        ("fill-rule", AId::FillRule),
        ("stroke", AId::Stroke),
        ("visibility", AId::Visibility),
        ("font-style", AId::FontStyle),
        ("y1", AId::Y1),
        ("stroke-linejoin", AId::StrokeLinejoin),
        ("refY", AId::RefY),
        ("rotate", AId::Rotate),
        ("systemLanguage", AId::SystemLanguage),
        ("stroke-dasharray", AId::StrokeDasharray),
        ("startOffset", AId::StartOffset),
        ("points", AId::Points),
        ("r", AId::R),
        ("font-family", AId::FontFamily),
        ("href", AId::Href),
        ("requiredFeatures", AId::RequiredFeatures),
        ("gradientTransform", AId::GradientTransform),
        ("font-variant", AId::FontVariant),
        ("fy", AId::Fy),
        ("font-stretch", AId::FontStretch),
        ("text-decoration", AId::TextDecoration),
        ("filter", AId::Filter),
        ("maskUnits", AId::MaskUnits),
        ("marker-end", AId::MarkerEnd),
        ("in", AId::In),
        ("viewBox", AId::ViewBox),
        ("patternUnits", AId::PatternUnits),
        ("space", AId::Space),
        ("fill", AId::Fill),
        ("stroke-width", AId::StrokeWidth),
        ("offset", AId::Offset),
        ("filterUnits", AId::FilterUnits),
        ("x", AId::X),
        ("gradientUnits", AId::GradientUnits),
        ("primitiveUnits", AId::PrimitiveUnits),
        ("spreadMethod", AId::SpreadMethod),
        ("operator", AId::Operator),
        ("font-weight", AId::FontWeight),
        ("x2", AId::X2),
        ("refX", AId::RefX),
        ("stdDeviation", AId::StdDeviation),
        ("patternContentUnits", AId::PatternContentUnits),
        ("height", AId::Height),
        ("marker-start", AId::MarkerStart),
        ("tableValues", AId::TableValues),
        ("class", AId::Class),
        ("maskContentUnits", AId::MaskContentUnits),
        ("flood-opacity", AId::FloodOpacity),
        ("markerHeight", AId::MarkerHeight),
        ("style", AId::Style),
        ("writing-mode", AId::WritingMode),
        ("type", AId::Type),
        ("patternTransform", AId::PatternTransform),
        ("dx", AId::Dx),
        ("markerWidth", AId::MarkerWidth),
        ("amplitude", AId::Amplitude),
        ("y", AId::Y),
        ("mask", AId::Mask),
        ("stroke-opacity", AId::StrokeOpacity),
        ("exponent", AId::Exponent),
        ("fill-opacity", AId::FillOpacity),
        ("k2", AId::K2),
        ("text-anchor", AId::TextAnchor),
        ("shape-rendering", AId::ShapeRendering),
        ("display", AId::Display),
        ("font-size", AId::FontSize),
        ("direction", AId::Direction),
        ("rx", AId::Rx),
        ("orient", AId::Orient),
        ("width", AId::Width),
        ("mode", AId::Mode),
        ("result", AId::Result),
        ("opacity", AId::Opacity),
        ("overflow", AId::Overflow),
        ("dy", AId::Dy),
        ("k4", AId::K4),
        ("markerUnits", AId::MarkerUnits),
        ("color-interpolation-filters", AId::ColorInterpolationFilters),
        ("x1", AId::X1),
        ("clip-rule", AId::ClipRule),
        ("image-rendering", AId::ImageRendering),
        ("y2", AId::Y2),
        ("k3", AId::K3),
        ("intercept", AId::Intercept),
    ],
};

impl AId {
    pub fn from_str(text: &str) -> Option<AId> {
        ATTRIBUTES.get(text).cloned()
    }

    #[inline(never)]
    pub fn to_str(&self) -> &'static str {
        ATTRIBUTES.key(self)
    }
}

impl fmt::Debug for AId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.to_str())
    }
}

impl fmt::Display for AId {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

// A stripped down `phf` crate fork.
//
// https://github.com/sfackler/rust-phf

struct Map<V: 'static> {
    pub key: u64,
    pub disps: &'static [(u32, u32)],
    pub entries: &'static[(&'static str, V)],
}

impl<V: PartialEq> Map<V> {
    fn get(&self, key: &str) -> Option<&V> {
        use std::borrow::Borrow;

        let hash = hash(key, self.key);
        let index = get_index(hash, &*self.disps, self.entries.len());
        let entry = &self.entries[index as usize];
        let b = entry.0.borrow();
        if b == key {
            Some(&entry.1)
        } else {
            None
        }
    }

    fn key(&self, value: &V) -> &'static str {
        self.entries.iter().find(|kv| kv.1 == *value).unwrap().0
    }
}

#[inline]
fn hash(x: &str, key: u64) -> u64 {
    use std::hash::Hasher;

    let mut hasher = siphasher::sip::SipHasher13::new_with_keys(0, key);
    hasher.write(x.as_bytes());
    hasher.finish()
}

#[inline]
fn get_index(hash: u64, disps: &[(u32, u32)], len: usize) -> u32 {
    let (g, f1, f2) = split(hash);
    let (d1, d2) = disps[(g % (disps.len() as u32)) as usize];
    displace(f1, f2, d1, d2) % (len as u32)
}

#[inline]
fn split(hash: u64) -> (u32, u32, u32) {
    const BITS: u32 = 21;
    const MASK: u64 = (1 << BITS) - 1;

    ((hash & MASK) as u32,
     ((hash >> BITS) & MASK) as u32,
     ((hash >> (2 * BITS)) & MASK) as u32)
}

#[inline]
fn displace(f1: u32, f2: u32, d1: u32, d2: u32) -> u32 {
    d2 + f1 * d1 + f2
}
