[package]
name = "benchmark"
version = "0.1.0"
edition = "2018"
workspace = "../.."

[dependencies]
svgrtypes = { path = "../" }
bencher = "0.1"

[[bench]]
name = "benchmark"
path = "benchmark.rs"
harness = false
